app:
    resource: "@AppBundle/Controller/"
    type:     annotation

re_index:
  path:       /tvseries
  defaults: { _controller: AppBundle:TvSeries:index }

re_logout:
    path:     /logout
    defaults: { _controller: AppBundle:Security:logout }

re_login:
    path:     /log
    defaults: { _controller: AppBundle:Security:login }

re_user:
    path:     /user
    defaults: { _controller: AppBundle:Security:user }